﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace AuthAPI
{
    public partial class SAnalyzer
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Text.FeaturizeText(@"tweet_text", @"tweet_text")      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"emotion_in_tweet_is_directed_at", @"emotion_in_tweet_is_directed_at"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"tweet_text",@"emotion_in_tweet_is_directed_at"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"is_there_an_emotion_directed_at_a_brand_or_product", @"is_there_an_emotion_directed_at_a_brand_or_product"))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.LbfgsLogisticRegression(l1Regularization:1F,l2Regularization:1F,labelColumnName:@"is_there_an_emotion_directed_at_a_brand_or_product",featureColumnName:@"Features"), labelColumnName: @"is_there_an_emotion_directed_at_a_brand_or_product"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
