// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AuthAPI
{
    public partial class SAnalyzer
    {
        /// <summary>
        /// model input class for SAnalyzer.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"tweet_text")]
            public string Tweet_text { get; set; }

            [ColumnName(@"emotion_in_tweet_is_directed_at")]
            public string Emotion_in_tweet_is_directed_at { get; set; }

            [ColumnName(@"is_there_an_emotion_directed_at_a_brand_or_product")]
            public string Is_there_an_emotion_directed_at_a_brand_or_product { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SAnalyzer.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public string Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SAnalyzer.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
